/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pantallas;

import static pantallas.metodos.conn;
import static pantallas.metodos.connect;
import static pantallas.metodos.st;
import config.bdConn;
import static config.bdConn.conn;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.util.Date;


public class listaVehiculos extends javax.swing.JPanel {


    public static String strDate;


    /**
     * Creates new form listaVehiculos
     */
    public listaVehiculos() {
        
        initComponents();
        tabla.getColumnModel().getColumn(0).setPreferredWidth(20); 
        tabla.getColumnModel().getColumn(1).setPreferredWidth(25);
        tabla.getColumnModel().getColumn(6).setPreferredWidth(20);
        tabla.getColumnModel().getColumn(7).setPreferredWidth(30);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public static void mostrarTabla(){
        String sql= "SELECT * FROM parkingappdb";

        try{
            connect = bdConn.getConnection();

            st=connect.prepareStatement(sql);
            ResultSet rs = st.executeQuery();
            DefaultTableModel model = (DefaultTableModel)tabla.getModel();
            model.setRowCount(0);
            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getString(6), rs.getString(7),rs.getString(8)});

            }
        }catch(Exception e){e.printStackTrace();}
        
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgingresosalida = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPlaca = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPropietario = new javax.swing.JTextPane();
        jLabel3 = new javax.swing.JLabel();
        calendar = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        rbEstacionado = new javax.swing.JRadioButton();
        rbRetirado = new javax.swing.JRadioButton();
        cbCarro = new javax.swing.JCheckBox();
        cbMoto = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setBackground(new java.awt.Color(244, 244, 244));
        setPreferredSize(new java.awt.Dimension(705, 768));

        bgingresosalida.setBackground(new java.awt.Color(244, 244, 244));
        bgingresosalida.setPreferredSize(new java.awt.Dimension(705, 768));

        jLabel2.setText("Placa");

        txtPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPlacaKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(txtPlaca);

        jScrollPane3.setViewportView(txtPropietario);

        jLabel3.setText("Propietario");

        calendar.setDateFormatString("d MMM yyyy       ");

        jLabel4.setText("Fecha");

        rbEstacionado.setText("ESTACIONADO");

        rbRetirado.setText("RETIRADO");
        rbRetirado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbRetiradoActionPerformed(evt);
            }
        });

        cbCarro.setText("CARRO");

        cbMoto.setText("MOTO");

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("BUSCAR VEHICULOS");

        jButton1.setText("Buscar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Placa", "Propietario", "Tipo de Vehiculo", "Hora entrada", "Hora salida", "Pago", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout bgingresosalidaLayout = new javax.swing.GroupLayout(bgingresosalida);
        bgingresosalida.setLayout(bgingresosalidaLayout);
        bgingresosalidaLayout.setHorizontalGroup(
            bgingresosalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgingresosalidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(bgingresosalidaLayout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(72, 72, 72)
                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(252, 252, 252))
            .addGroup(bgingresosalidaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(bgingresosalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgingresosalidaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(19, 19, 19))
                    .addGroup(bgingresosalidaLayout.createSequentialGroup()
                        .addGroup(bgingresosalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgingresosalidaLayout.createSequentialGroup()
                                .addComponent(cbMoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(cbCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(314, 314, 314)
                                .addComponent(rbEstacionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(26, 26, 26)
                                .addComponent(rbRetirado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(bgingresosalidaLayout.createSequentialGroup()
                                .addGroup(bgingresosalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgingresosalidaLayout.createSequentialGroup()
                                        .addGap(98, 98, 98)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(100, 100, 100))
                                    .addGroup(bgingresosalidaLayout.createSequentialGroup()
                                        .addGap(67, 67, 67)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(bgingresosalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgingresosalidaLayout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(34, 34, 34))
                                    .addComponent(jScrollPane3))
                                .addGroup(bgingresosalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgingresosalidaLayout.createSequentialGroup()
                                        .addGap(108, 108, 108)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(124, 124, 124))
                                    .addGroup(bgingresosalidaLayout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(25, 25, 25))))
        );
        bgingresosalidaLayout.setVerticalGroup(
            bgingresosalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgingresosalidaLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(75, 75, 75)
                .addGroup(bgingresosalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(bgingresosalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(calendar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addGroup(bgingresosalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbRetirado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(bgingresosalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbMoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(rbEstacionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(bgingresosalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgingresosalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgingresosalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlacaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaKeyPressed

    }//GEN-LAST:event_txtPlacaKeyPressed

    private void rbRetiradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbRetiradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbRetiradoActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String placa = txtPlaca.getText();
        String propietario = txtPropietario.getText();
        String estado = null;
        String tipoVehiculo= null;

        StringBuilder query = new StringBuilder("SELECT * FROM parkingappdb WHERE 1=1");

        if(!placa.equals("")){
            query.append(" AND placa LIKE ?");
        }

        if(!propietario.equals("")){
            query.append(" AND propietario LIKE ?");
        }

        if(calendar.getDate()!=null){
            query.append(" AND horaEntrada LIKE ?");
            Date date = calendar.getDate();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            strDate = dateFormat.format(date);
            System.out.print(strDate);
        }

        if(rbEstacionado.isSelected() && rbRetirado.isSelected() || !rbEstacionado.isSelected() && !rbRetirado.isSelected()){
            query.append(" AND estado IN ('estacionado', 'retirado')");
        }else{
            if(rbEstacionado.isSelected() && !rbRetirado.isSelected()){
                query.append(" AND estado = 'estacionado'");
            }else{
                query.append(" AND estado = 'retirado'");
            }
        }

        if(cbCarro.isSelected() && cbMoto.isSelected() || !cbCarro.isSelected() && !cbMoto.isSelected()){
            query.append(" AND tipovehiculo IN ('carro', 'moto')");
        }else{
            if(cbCarro.isSelected() && !cbMoto.isSelected()){
                query.append(" AND tipovehiculo = 'carro'");
            }else{
                query.append(" AND tipovehiculo = 'moto'");
            }
        }
        try{
            PreparedStatement statement = connect.prepareStatement(query.toString());

            int stringValor = 1;

            if(!placa.equals("")){
                statement.setString(stringValor++, "%" + placa + "%");
            }

            if(!propietario.equals("")){
                statement.setString(stringValor++, "%" + propietario + "%");
            }

            if(calendar.getDate()!=null){
                statement.setString(stringValor++, "%" + strDate + "%");

            }

            ResultSet resultset = statement.executeQuery();
            DefaultTableModel model = (DefaultTableModel)tabla.getModel();
            model.setRowCount(0);
            while(resultset.next()){
                model.addRow(new String[]{resultset.getString(1), resultset.getString(2), resultset.getString(3), resultset.getString(4), resultset.getString(5), resultset.getString(6), resultset.getString(7),resultset.getString(8)});
            }
        }catch(Exception e){e.printStackTrace();}

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        rbEstacionado.setSelected(false);
        rbRetirado.setSelected(false);
        cbMoto.setSelected(false);
        cbCarro.setSelected(false);
        txtPlaca.setText("");
        txtPropietario.setText("");
        calendar.setCalendar(null);
        mostrarTabla();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgingresosalida;
    private com.toedter.calendar.JDateChooser calendar;
    private javax.swing.JCheckBox cbCarro;
    private javax.swing.JCheckBox cbMoto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rbEstacionado;
    private javax.swing.JRadioButton rbRetirado;
    private static javax.swing.JTable tabla;
    private javax.swing.JTextPane txtPlaca;
    private javax.swing.JTextPane txtPropietario;
    // End of variables declaration//GEN-END:variables
}
